export const digitalMarketingPoints = [
  {
    id: 0,
    title: "Introduction to Digital Marketing",
    content: [
      "Definition and importance",
      "Key channels and platforms",
      "Emerging trends (e.g., AI, automation)",
    ],
  },
  {
    id: 1,
    title: "Content Marketing",
    content: [
      "Content strategy and planning",
      "Types of content: blog posts, videos, infographics, interactive content",
      "Content creation and curation",
      "Content distribution and promotion",
      "Use of AI and machine learning for content creation",
    ],
  },
  {
    id: 2,
    title: "Search Engine Optimization (SEO)",
    content: [
      "On-page SEO: keywords, meta tags, headers",
      "Off-page SEO: backlinks, social signals",
      "Technical SEO: site speed, mobile-friendliness, schema markup",
      "SEO tools and analytics",
      "Voice search optimization",
      "AI-driven SEO tools",
    ],
  },
  {
    id: 3,
    title: "Social Media Marketing",
    content: [
      "Platform-specific strategies (Facebook, Instagram, LinkedIn, Twitter, TikTok)",
      "Content creation and scheduling",
      "Social media advertising and promotions",
      "Engagement and community management",
      "Use of chatbots and automated responses",
      "Social listening tools and sentiment analysis",
    ],
  },
  {
    id: 4,
    title: "Email Marketing",
    content: [
      "Building and segmenting email lists",
      "Crafting effective email campaigns",
      "A/B testing and optimization",
      "Analytics and performance tracking",
      "Use of AI for personalization and automation",
      "Integration with CRM systems",
    ],
  },
  {
    id: 5,
    title: "Pay-Per-Click (PPC) Advertising",
    content: [
      "Google Ads and Bing Ads",
      "Ad targeting and bidding strategies",
      "Ad copywriting and design",
      "Conversion tracking and ROI measurement",
      "Use of AI for ad optimization",
      "Programmatic advertising",
    ],
  },
  {
    id: 6,
    title: "Analytics and Data Analysis",
    content: [
      "Google Analytics and other tools",
      "Key metrics and KPIs",
      "Data interpretation and reporting",
      "Making data-driven decisions",
      "Advanced analytics: predictive analytics, AI-driven insights",
      "Data privacy and compliance (e.g., GDPR, CCPA)",
    ],
  },
  {
    id: 7,
    title: "Conversion Rate Optimization (CRO)",
    content: [
      "Landing page design and testing",
      "User experience (UX) and usability",
      "A/B testing and multivariate testing",
      "Analyzing and improving conversion paths",
      "Use of AI for personalization and behavioral targeting",
    ],
  },
  {
    id: 8,
    title: "Affiliate and Influencer Marketing",
    content: [
      "Identifying and partnering with affiliates/influencers",
      "Managing campaigns and relationships",
      "Tracking performance and ROI",
      "Influencer marketing platforms and tools",
      "AI for influencer matchmaking and analytics",
    ],
  },
  {
    id: 9,
    title: "Digital Marketing Strategy and Planning",
    content: [
      "Setting goals and objectives",
      "Budgeting and resource allocation",
      "Creating and executing a marketing plan",
      "Monitoring and adjusting strategies",
      "Use of AI and automation in strategy development",
    ],
  },
  {
    id: 10,
    title: "New Technologies and Innovations",
    content: [
      "Blockchain in digital marketing (e.g., ad fraud prevention)",
      "Augmented Reality (AR) and Virtual Reality (VR) for immersive experiences",
      "Internet of Things (IoT) and connected devices",
      "Advanced chatbots and conversational AI",
      "5G technology and its impact on digital marketing",
    ],
  },
];
